apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
