apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.app }}
    spec:
      containers:
        - name: {{ .Values.api.app }}
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
